import img_01 from "../../assets/images/Abdulla Avloniy.png";
import img_02 from "../../assets/images/Nusrat Rahmat.png";
import img_03 from "../../assets/images/Rahmonberdi Madazimov.png";
import img_04 from "../../assets/images/Hamza Hakimzoda Niyoziy.png";
import img_05 from "../../assets/images/Abdulhamid Cholpon.png";
import img_06 from "../../assets/images/Abdurauf Fitrat.png";
import img_07 from "../../assets/images/Abdulmajid Qodiriy.png";
import img_08 from "../../assets/images/Munavvar qori Abdurashidxonov.png";
import img_09 from "../../assets/images/Abdulla Qodiriy.png";
import img_10 from "../../assets/images/Mahmuxo’ja Behbudiy.png";
import img_11 from "../../assets/images/Hoji Muin.png";

export const TabData = [
  {
    id: 1,
    link_img: img_01,
    year: "1878 - 1934",
    title: "Abdulla Avloniy",
    books: 34,
    audio_books: 13,
    category: "sovet-davri",
  },
  {
    id: 2,
    link_img: img_02,
    year: "1878 - 1934",
    title: "Nusrat Rahmat",
    books: 34,
    audio_books: 13,
    category: "sovet-davri",
  },
  {
    id: 3,
    link_img: img_03,
    year: "1878 - 1934",
    title: "Rahmonberdi Madazimov",
    books: 34,
    audio_books: 13,
    category: "sovet-davri",
  },
  {
    id: 4,
    link_img: img_04,
    year: "1878 - 1934",
    title: "Hamza Hakimzoda Niyoziy",
    books: 34,
    audio_books: 13,
    category: "sovet-davri",
  },
  {
    id: 5,
    link_img: img_05,
    year: "1878 - 1934",
    title: "Abdulhamid Cho'lpon",
    books: 34,
    audio_books: 13,
    category: "sovet-davri",
  },
  {
    id: 6,
    link_img: img_06,
    year: "1878 - 1934",
    title: "Abdurauf Fitrat",
    books: 34,
    audio_books: 13,
    category: "sovet-davri",
  },
  {
    id: 7,
    link_img: img_07,
    year: "1878 - 1934",
    title: "Abdulmajid Qodiriy",
    books: 34,
    audio_books: 13,
    category: "sovet-davri",
  },
  {
    id: 8,
    link_img: img_08,
    year: "1878 - 1934",
    title: "Munavvarqori Abdurashidxonov",
    books: 34,
    audio_books: 13,
    category: "sovet-davri",
  },
  {
    id: 9,
    link_img: img_09,
    year: "1878 - 1934",
    title: "Abdulla Qodiriy",
    books: 34,
    audio_books: 13,
    category: "sovet-davri",
  },
  {
    id: 10,
    link_img: img_10,
    year: "1878 - 1934",
    title: "Mahmuxo’ja Behbudiy",
    books: 34,
    audio_books: 13,
    category: "sovet-davri",
  },
  {
    id: 11,
    link_img: img_11,
    year: "1878 - 1934",
    title: "Hoji Muin",
    books: 34,
    audio_books: 13,
    category: "sovet-davri",
  },

  {
    id: 12,
    link_img: img_01,
    year: "1878 - 1934",
    title: "Abdulla Avloniy",
    books: 34,
    audio_books: 13,
    category: "temuriylar-davri",
  },
  {
    id: 13,
    link_img: img_02,
    year: "1878 - 1934",
    title: "Nusrat Rahmat",
    books: 34,
    audio_books: 13,
    category: "temuriylar-davri",
  },
  {
    id: 14,
    link_img: img_03,
    year: "1878 - 1934",
    title: "Rahmonberdi Madazimov",
    books: 34,
    audio_books: 13,
    category: "temuriylar-davri",
  },
  {
    id: 15,
    link_img: img_04,
    year: "1878 - 1934",
    title: "Hamza Hakimzoda Niyoziy",
    books: 34,
    audio_books: 13,
    category: "temuriylar-davri",
  },
  {
    id: 16,
    link_img: img_05,
    year: "1878 - 1934",
    title: "Abdulhamid Cho'lpon",
    books: 34,
    audio_books: 13,
    category: "temuriylar-davri",
  },
  {
    id: 17,
    link_img: img_06,
    year: "1878 - 1934",
    title: "Abdurauf Fitrat",
    books: 34,
    audio_books: 13,
    category: "temuriylar-davri",
  },
  {
    id: 18,
    link_img: img_07,
    year: "1878 - 1934",
    title: "Abdulmajid Qodiriy",
    books: 34,
    audio_books: 13,
    category: "temuriylar-davri",
  },
  {
    id: 19,
    link_img: img_08,
    year: "1878 - 1934",
    title: "Munavvarqori Abdurashidxonov",
    books: 34,
    audio_books: 13,
    category: "temuriylar-davri",
  },
  {
    id: 20,
    link_img: img_09,
    year: "1878 - 1934",
    title: "Abdulla Qodiriy",
    books: 34,
    audio_books: 13,
    category: "temuriylar-davri",
  },
  {
    id: 21,
    link_img: img_10,
    year: "1878 - 1934",
    title: "Mahmuxo’ja Behbudiy",
    books: 34,
    audio_books: 13,
    category: "temuriylar-davri",
  },
  {
    id: 22,
    link_img: img_11,
    year: "1878 - 1934",
    title: "Hoji Muin",
    books: 34,
    audio_books: 13,
    category: "temuriylar-davri",
  },
];
